Corrections from a code review
* Add curl flag to follow redirection URLs
* Extract the SVN base URL into a global variable/constant
* Use 'grep -E' instead of 'egrep' and ignoring the lint error
* Rework an exit code check to avoid having to ignore a lint error

diff --git a/bin/mkdevbranch b/bin/mkdevbranch
--- a/bin/mkdevbranch
+++ b/bin/mkdevbranch
@@ -3,6 +3,7 @@
 version=0.24
 program=${0##*/}
 progdir=${0%/*}
+svn_url_base="https://svn.ietf.org/svn/tools/ietfdb"
 if [ "$progdir" = "$program" ]; then progdir="."; fi
 
 # ----------------------------------------------------------------------
@@ -25,15 +26,13 @@ DESCRIPTION
 EOF
     echo -e "OPTIONS"
     if [ "$(uname)" = "Linux" ]; then
-        # shellcheck disable=SC2196
         # shellcheck disable=SC2086
         # shellcheck disable=SC2016
-        egrep "^\s+[-][A-Za-z| -]+\*?\)\s+[A-Za-z].+#" $0 | tr -s "\t|" "\t," | $sed -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
+        grep -E "^\s+[-][A-Za-z| -]+\*?\)\s+[A-Za-z].+#" "$0" | tr -s "\t|" "\t," | $sed -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
     else
-        # shellcheck disable=SC2196
         # shellcheck disable=SC2086
         # shellcheck disable=SC2016
-        egrep "^\s+[-][A-Za-z| -]+\*?\)\s+[A-Za-z].+#" $0 | $sed 's/\|.*\$2[^#]*#/	/' | $sed 's/\|.*\)[^#]*#/	/'
+        grep -E "^\s+[-][A-Za-z| -]+\*?\)\s+[A-Za-z].+#" "$0" | $sed 's/\|.*\$2[^#]*#/	/' | $sed 's/\|.*\)[^#]*#/	/'
     fi
     cat <<EOF
 
@@ -92,11 +91,11 @@ function check_svn_path_exists() {
 function mksvndir() {
     who=$1
     if [ "$2" ]; then dir=$2; else dir=$who; fi
-    check_svn_path_exists exists "https://svn.ietf.org/svn/tools/ietfdb/personal/$dir"
+    check_svn_path_exists exists "${svn_url_base}/personal/$dir"
     # shellcheck disable=SC2154
     if [ "$exists" != "0" ]; then
         $do echo "Creating personal directory area for IETF datatracker coding: /personal/$dir"
-        $do svn mkdir "https://svn.ietf.org/svn/tools/ietfdb/personal/$dir" -m "Personal SVN dir for $who, for IETF datatracker code"
+        $do svn mkdir "${svn_url_base}/personal/$dir" -m "Personal SVN dir for $who, for IETF datatracker code"
     else
         echo "Repository area personal/$dir is already in place."
     fi
@@ -109,11 +108,11 @@ function mksvntarget() {
     local email=$4
     local name=$5
 
-    check_svn_path_exists exists "https://svn.ietf.org/svn/tools/ietfdb/personal/$who/$target"
+    check_svn_path_exists exists "${svn_url_base}/personal/$who/$target"
     if [ "$exists" != "0" ]; then
         $do echo "  creating $target branch for $who ($name)."
-        $do svn cp "https://svn.ietf.org/svn/tools/ietfdb/$source" \
-            "https://svn.ietf.org/svn/tools/ietfdb/personal/$who/$target/" \
+        $do svn cp "${svn_url_base}/$source" \
+            "${svn_url_base}/personal/$who/$target/" \
             -m "New branch for $target"
         $do echo "New branch: ^/personal/$who/$target"
         if [ -n "$email" ]; then
@@ -136,9 +135,9 @@ function notify_user() {
 		This mail has been automatically generated by the $program script.
 
 		A new SVN branch has been set up for you for IETF datatracker coding, at
-		https://svn.ietf.org/svn/tools/ietfdb/personal/$login/$target
+		${svn_url_base}/personal/$login/$target
 		${rev:+This branch is based on $rev.  }You can check it out by doing
-		svn co https://svn.ietf.org/svn/tools/ietfdb/personal/$login/$target
+		svn co ${svn_url_base}/personal/$login/$target
 
 		There's also a database dump available at
 		https://www.ietf.org/lib/dt/sprint/ietf_utf8.sql.gz -- this dump is served
@@ -160,7 +159,7 @@ function notify_user() {
 function get_sprinters_info() {
     local n=$1
 
-    curl -s "https://trac.ietf.org/trac/ietfdb/wiki/IETF${n}SprintSignUp?format=txt" | \
+    curl -L -s "https://trac.ietf.org/trac/ietfdb/wiki/IETF${n}SprintSignUp?format=txt" | \
         grep -E "^\|\|" | \
         grep -Ev "^\|\|\s+\|\|\s+" | \
         tail -n +2 | \
@@ -170,7 +169,7 @@ function get_sprinters_info() {
 }
 
 # ----------------------------------------------------------------------
-trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR
+trap 'echo "$program($LINENO): Command failed with error code $? ([$$] "$0" $*)"; exit 1' ERR
 
 # ----------------------------------------------------------------------
 # Option parsing
@@ -187,9 +186,7 @@ do=""
 if [ "$(uname)" = "Linux" ]; then
     # shellcheck disable=SC2086
     # shellcheck disable=SC2048
-    args=$(getopt -o $short_options --long $long_options -n $program -- $SV $*)
-    # shellcheck disable=SC2181
-    if [ $? != 0 ]; then
+    if ! args=$(getopt -o $short_options --long $long_options -n $program -- $SV $*); then
         die "Terminating..." >&2
         exit 1
     fi
@@ -200,9 +197,7 @@ else
     # Darwin, BSDs
     # shellcheck disable=SC2086
     # shellcheck disable=SC2048
-    args=$(getopt -o$short_options $SV $*)
-    # shellcheck disable=SC2181
-    if [ $? != 0 ]; then
+    if ! args=$(getopt -o$short_options $SV $*); then
         die "Terminating..." >&2
         exit 1
     fi
@@ -245,7 +240,7 @@ done
 # The program itself
 
 who=""
-tag=$(svn log -v https://svn.ietf.org/svn/tools/ietfdb/tags/dev/ --limit 1 | grep '/tags/' | awk '{print $2}')
+tag=$(svn log -v ${svn_url_base}/tags/dev/ --limit 1 | grep '/tags/' | awk '{print $2}')
 
 source="${tag:1}"
 target="${tag##*/}"
@@ -266,7 +261,7 @@ if [ "$SPRINT" ]; then
     [ "$msg" ] && msg="
 $msg
 "
-    [ "$num" ] || num=$(curl -s "https://tools.ietf.org/meta/current-ietf-number.txt")
+    [ "$num" ] || num=$(curl -L -s "https://tools.ietf.org/meta/current-ietf-number.txt")
     for n in $(seq $((num - 3)) "$num"); do
         get_sprinters_info "$n"
     done
